INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (21,'Bu bir Çin dili Günaydın.',10000.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (22,'ve test nesnesidir Tünaydın.',2005.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (23,'Buenos días Hasta mañana',1008.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (24,'Feliz cumpleaños',2003.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (25,'Hola Buenos días',10010.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (26,'¿Cómo estás? Me gustaría',2009.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (27,'I cant even',10065.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (28,'No big deal',20098.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (29,'你叫什么名字',10098.0);
INSERT INTO XXTPI_AOM_TEST_EMP_TBL (emp_no,emp_name,salary) values (30,'你来自哪里  多少钱',20045.0);
commit;