  CREATE TABLE "AHL_SCH_MTLS_SN"
   (	"M_ROW$$" VARCHAR2(18),
	"INVENTORY_ITEM_ID" NUMBER,
	"ORGANIZATION_ID" NUMBER,
	"SCHEDULED_MATERIAL_ID" NUMBER NOT NULL ENABLE,
	"HEADER_ID" NUMBER,
	"VISIT_TASK_ID" NUMBER,
	"REQUESTED_QUANTITY" NUMBER NOT NULL ENABLE,
	"COMPLETED_QUANTITY" NUMBER,
	"REQUESTED_DATE" DATE NOT NULL ENABLE,
	"OPERATION_SEQUENCE" NUMBER,
	"ATP_FLAG" VARCHAR2(1),
	"RN" NUMBER
   ) ;
