  CREATE GLOBAL TEMPORARY TABLE "AMS_INFMET_ORDER_GT"
   (	"PRIMARY_PARTY_ID" NUMBER,
	"CONTACT_REL_PARTY_ID" NUMBER,
	"LAST_ACTIVATION_DATE" DATE,
	"ACTIVITY_METRIC_ID" NUMBER,
	"SOURCE_CATEGORY" VARCHAR2(3),
	"OBJECT_ID" NUMBER
   ) ON COMMIT PRESERVE ROWS ;
