  CREATE TABLE "BIM_R_LIMP_REG_DIM_MV_TEMP"
   (	"LEAD_REGION" VARCHAR2(30),
	"LEAD_COUNTRY" VARCHAR2(30),
	"YEAR" VARCHAR2(30),
	"QTR" VARCHAR2(30),
	"MONTH" VARCHAR2(30),
	"MONTH_ORDER" NUMBER,
	"AGGREGATE_BY" VARCHAR2(9),
	"DISPLAY_TYPE" VARCHAR2(5),
	"LEADS_VALID" NUMBER,
	"LEADS_INVALID" NUMBER,
	"LEADS_NEW" NUMBER,
	"LEADS_ADDED" NUMBER,
	"PREV_LEADS_VALID" NUMBER,
	"PREV_LEADS_INVALID" NUMBER,
	"PREV_LEADS_NEW" NUMBER,
	"PREV_LEADS_ADDED" NUMBER
   )
  PARALLEL 4 ;
