  CREATE TABLE "DDR_BS_FRCST_VRSN_MV"
   (	"MFG_ORG_CD" VARCHAR2(30) NOT NULL ENABLE,
	"RTL_ORG_CD" VARCHAR2(30) NOT NULL ENABLE,
	"ORG_BSNS_UNIT_ID" NUMBER NOT NULL ENABLE,
	"MFG_SKU_ITEM_ID" NUMBER,
	"RTL_SKU_ITEM_ID" NUMBER NOT NULL ENABLE,
	"DAY_CD" VARCHAR2(30) NOT NULL ENABLE,
	"FRCST_PURP" VARCHAR2(30),
	"FRCST_TYP" VARCHAR2(30) NOT NULL ENABLE,
	"MAX_FRCST_VRSN" DATE,
	"CNT_TOTAL" NUMBER
   ) ;
