  CREATE OR REPLACE EDITIONABLE TYPE "ACTION_INPUT_DATA_OBJ" FORCE AS OBJECT ( dataSetType VARCHAR2 ( 50 ) , dataSetId NUMBER, name VARCHAR2 ( 4000 ) , value VARCHAR2 ( 4000 ) , type VARCHAR2 ( 4000 ) )
/
