  CREATE TABLE "BA_ENTITY_RELATIONS"
   (	"BA_ENTITY_RELATION_ID" NUMBER,
	"BUSINESS_ACTIVITY_ID" NUMBER,
	"ENTITY_ID" NUMBER,
	"SOURCE_SYSTEM" VARCHAR2(255),
	"ENTITY_VALUE" VARCHAR2(255),
	"INPUT_OUTPUT_DELETE" VARCHAR2(255),
	"TESTING_LABEL" VARCHAR2(1000),
	"TESTING_VALUE" VARCHAR2(1000),
	"TESTING_INPUT_TYPE" VARCHAR2(255),
	"TESTING_INPUT_TYPE_VALUE" VARCHAR2(1000)
   ) ;
