DROP MATERIALIZED VIEW BOM_RES_INST_CHNGS_SN;
  CREATE MATERIALIZED VIEW "BOM_RES_INST_CHNGS_SN" ("DEPARTMENT_ID", "RESOURCE_ID", "INSTANCE_ID", "SHIFT_NUM", "FROM_DATE", "TO_DATE", "FROM_TIME", "TO_TIME", "CAPACITY_CHANGE", "SIMULATION_SET", "ACTION_TYPE", "SERIAL_NUMBER", "RN", "BO_ROWID", "BD_ROWID", "ORGANIZATION_ID")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_NOLOGGING"
  BUILD DEFERRED
  USING INDEX
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS EVALUATE USING CURRENT EDITION  DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "A2"."DEPARTMENT_ID" "DEPARTMENT_ID","A2"."RESOURCE_ID" "RESOURCE_ID","A2"."INSTANCE_ID" "INSTANCE_ID","A2"."SHIFT_NUM" "SHIFT_NUM","A2"."FROM_DATE" "FROM_DATE","A2"."TO_DATE" "TO_DATE","A2"."FROM_TIME" "FROM_TIME","A2"."TO_TIME" "TO_TIME","A2"."CAPACITY_CHANGE" "CAPACITY_CHANGE","A2"."SIMULATION_SET" "SIMULATION_SET","A2"."ACTION_TYPE" "ACTION_TYPE","A2"."SERIAL_NUMBER" "SERIAL_NUMBER",0 "RN","A2".ROWID "BO_ROWID","A1".ROWID "BD_ROWID","A1"."ORGANIZATION_ID" "ORGANIZATION_ID" F
ROM "BOM"."BOM_RES_INSTANCE_CHANGES" "A2","BOM"."BOM_DEPARTMENTS" "A1" WHERE "A2"."DEPARTMENT_ID"="A1"."DEPARTMENT_ID";
