  CREATE OR REPLACE EDITIONABLE VIEW "BPM_MODEL_NODE_MAPPING_V" ("CATEGORY_NAME", "MODEL_NAME", "NODE_NAME", "NODE_TYPE") AS
  SELECT VW.CATEGORY_NAME,
VW.MODEL_NAME,
NODES.NODE_NAME,
DECODE(NODES.NODE_TYPE, 'TRI2_BPM_SUBPROCESS', 'BP', 'BA') NODE_TYPE
FROM STATEGPS.BPM_MODELS_REPORT_V VW, STATEGPS.T_GPS_NODES NODES
WHERE NODES.MODEL_ID = VW.MODEL_ID
AND NODES.NODE_TYPE NOT IN
('LINE', 'TRI2_BPM_START', 'TRI2_BPM_END', 'TRI2_BPM_DECISION_BOX',
     'Forward Connector', 'TRI2_BPM_DECISION_BOX_AND',
        'TRI2_BPM_SUBPROCESS')
   AND NODES.Acd_Flag != 'D'
   AND
 exists (select  r.model_id from stategps.t_gps_node_model_relations r where r.model_id=vw.model_id)
        /*AND VW.MODEL_NAME = '1.2 TFSS GL Closing Process'
   AND VW.CATEGORY_ID = 410;*/
;
