<?xml version = '1.0' encoding = 'utf-8'?>
<!--Generated by Oracle BI Publisher 10.1.3.4.2-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="66.6pt" margin-right="30.6pt" page-height="612.0pt" page-width="792.0pt" margin-top="36.0pt" margin-bottom="36.0pt">
               <fo:region-before region-name="region-header" extent="54.0pt"/>
               <fo:region-body region-name="region-body" margin-top="54.0pt" margin-bottom="9.35pt"/>
               <fo:region-after region-name="region-footer" extent="9.35pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0" initial-page-number="{1}">
            <fo:title>Offline Report</fo:title>
            <xsl:variable name="_PW" select="number(792.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(612.0)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(90.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(45.35)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header">
               <fo:block padding-bottom="0.0pt" padding-top="0.0pt">
                  <fo:table start-indent="5.4pt" style-id="ts-1" xdofo:align="start" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0" keep-together.within-page="always">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="180.0pt"/>
                     <fo:table-column column-width="324.0pt"/>
                     <fo:table-column column-width="99.0pt"/>
                     <fo:table-column column-width="81.0pt"/>
                     <fo:table-body>
                        <fo:table-row keep-together="always">
                           <fo:table-cell padding-end="0.0pt" padding-bottom="0.0pt" padding-start="0.0pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" number-rows-spanned="2">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt" start-indent="0.0pt" xdofo:xliff-id="7b67bbb8" xdofo:xliff-idx="0">
                                 <fo:instream-foreign-object content-type="image/png" width="66.240005pt" height="10.8pt" xdofo:alt="An Image" xdofo:image-uid="8ba2db62803fd7629d2a361e0d3106cc">iVBORw0KGgoAAAANSUhEUgAAAFwAAAAPCAMAAABeK1gzAAAAYFBMVEX/////zMz/
fID/Zmb/mZnq6ur/UFD//8z4+Pjn59bx8fH/AAD/MzP/+/D/zJn/MwDv1sb/ADNV
VVVNTU1CQkI5OTn/fID/UFDWAJPM7P/v1sbn59atqZAzAABmAACZAAA4BuMWAAAA
AWJLR0QAiAUdSAAAAAxjbVBQSkNtcDA3MTIAAAADSABzvAAAAXxJREFUOE/NVNFu
BCEIPMSl3uretf//s51RULd9blKSTUBwGEayj8ff2yFuB3tdEYms1ptfZh5e2dmt
myWuin1Vt6Y4lIhqbVGTanX3yi3y6ZinbHGmmcnZb2bUNrcOB/AVD0j2aye9YjNr
17mDH4D2e1rEPv2eBb8irbYi+Mawh1XtiK1aq4kuqOTexe8u5ay2vES6eoFOKEbP
d5UFDqjGU4hyAhVAoJeXyjtzDLc9kdfcqomTAH4OCqdVG6IAEcwK3JiqT7YBorma
m/psmPjW0MFzYx1UZHKIA9IpRnFiP8DnInQBaS7rCjPZgTOtvzm0ydw+Rav7fuwR
ZQmbwg0tw7hyAMe+49z6FlMUblRvBi423/Mmy9XG49/sAkfNbvBT6Ep04HBT8OwQ
SZl9okN6eTmfdxkzHr3GsuA2xl0GuSBDnwV7WeWiGMGGU/LUTSHLCjjrzCz+ktQt
E0c09d8AHEsfqmv3SkLwzFEtj+kqF0QiTLefwi+x/v3BN8ZhElMQYtpPAAAAAElF
TkSuQmCC</fo:instream-foreign-object>
                                 <fo:inline height="12.0pt" white-space-collapse="false" font-size="12.0pt" color="#336699" font-family="Arial">User Management</fo:inline>
                              </fo:block>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" font-size="12.0pt" height="12.0pt" font-family="Courier New"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="0.0pt" padding-bottom="0.0pt" padding-start="0.0pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" number-rows-spanned="2">
                              <fo:block height="14.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="0.0pt" padding-bottom="0.0pt" padding-start="0.0pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="d40f1c60" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">Report Date:</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="0.0pt" padding-bottom="0.0pt" padding-start="0.0pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                    <xsl:value-of select="xdoxslt:sysdate('DD-MON-YYYY HH24:MI')" xdofo:field-name="xdoxslt:sysdate('DD-MON-YYYY HH24:MI')"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row keep-together="always">
                           <fo:table-cell padding-end="0.0pt" padding-bottom="0.0pt" padding-start="0.0pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="2">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt" start-indent="0.0pt" xdofo:xliff-id="d27b58e7" xdofo:xliff-idx="0">
                                 <fo:inline xml:space="preserve" height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">Page <fo:page-number/> of <fo:page-number-citation ref-id="xdofo:lastpage-joinseq"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:tab-stops="center:216.0pt:space right:432.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt" font-size="12.0pt" height="13.392pt" font-family="Times New Roman"/>
               <fo:block xdofo:tab-stops="center:216.0pt:space right:432.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt">
                  <fo:table start-indent="5.0pt" style-id="ts-1" xdofo:align="start" xdofo:table-summary="Template Table 2" xdofo:row-header-count="0" keep-together.within-page="always">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="180.4pt"/>
                     <fo:table-column column-width="503.6pt"/>
                     <fo:table-body>
                        <fo:table-row keep-together="always">
                           <fo:table-cell padding-end="0.0pt" padding-bottom="0.0pt" padding-start="0.0pt" padding-top="0.0pt" vertical-align="middle" height="11.3pt" number-columns-spanned="1">
                              <fo:block xdofo:header-level="6" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="3.6pt" padding-top="0.0pt" keep-with-next.within-page="always" start-indent="0.0pt" xdofo:xliff-id="9577085f" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Users who have access to Function</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="0.0pt" padding-bottom="0.0pt" padding-start="0.0pt" padding-top="0.0pt" vertical-align="top" height="11.3pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" color="#000000">
                                    <xsl:value-of select=".//PARAM1" xdofo:field-name="PARAM1"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:tab-stops="center:216.0pt:space right:432.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt" font-size="12.0pt" height="13.392pt" font-family="Times New Roman"/>
            </fo:static-content>
            <fo:static-content flow-name="region-footer"/>
            <fo:flow flow-name="region-body">
               <fo:block padding-bottom="0.25pt" padding-top="0.25pt">
                  <fo:table start-indent="0.0pt" style-id="ts-1" xdofo:align="start" xdofo:table-summary="Template Table 3" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="95.4pt"/>
                     <fo:table-column column-width="54.0pt"/>
                     <fo:table-column column-width="54.0pt"/>
                     <fo:table-column column-width="70.85pt"/>
                     <fo:table-column column-width="64.15pt"/>
                     <fo:table-column column-width="72.0pt"/>
                     <fo:table-column column-width="63.0pt"/>
                     <fo:table-column column-width="189.0pt"/>
                     <fo:table-header>
                        <fo:table-row keep-with-next="always">
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#72a1c8">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="24eeab" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Name</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#72a1c8">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="c87494cf" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Created By</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#72a1c8">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="9f3e884f" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Creation Date</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#72a1c8">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="e552a1c6" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Last Updated By</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#72a1c8">
                              <fo:block xdofo:tab-stops="left:335.25pt:space" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="c1542a3b" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Last Update Date</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#72a1c8">
                              <fo:block xdofo:tab-stops="left:335.25pt:space" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="2a3b005b" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Accessible Through</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#72a1c8">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="32c977d6" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Accessible</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#72a1c8">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" xdofo:xliff-id="91aa7e64" xdofo:xliff-idx="0">
                                 <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt" font-weight="bold">Reason</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-header>
                     <fo:table-body>
                        <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                        <xsl:variable name="_XDOFOTOTAL" select="count(.//G_WITH)"/>
                        <xsl:for-each select=".//G_WITH" xdofo:ctx="3">
                           <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                           <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                           <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                           <xsl:variable name="_XDOFOTOTAL" select="count(.//G_WITH1)"/>
                           <xsl:for-each select=".//G_WITH1" xdofo:ctx="3">
                              <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                              <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                              <fo:table-row xdofo:repeat="RR">
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="F, NAME" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt" start-indent="0.0pt">
                                       <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                          <xsl:value-of select=".//ancestor-or-self::*/NAME" xdofo:field-name="ancestor-or-self::*/NAME"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="CREATEDBY" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt" start-indent="0.0pt">
                                       <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                          <xsl:value-of select=".//ancestor-or-self::*/CREATEDBY" xdofo:field-name="ancestor-or-self::*/CREATEDBY"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt" start-indent="0.0pt">
                                       <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                          <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv1">
                                             <xsl:value-of select=".//ancestor-or-self::*/CREATIONDATE" xdofo:field-name="ancestor-or-self::*/CREATIONDATE"/>
                                          </xsl:variable>
                                          <xsl:value-of select="xdoxslt:ms_format_date($_XDOXSLTCTX, string($fv1), 'yyyy-MM-dd')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="LASTUPDATEDBY" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt" start-indent="0.0pt">
                                       <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                          <xsl:value-of select=".//ancestor-or-self::*/LASTUPDATEDBY" xdofo:field-name="ancestor-or-self::*/LASTUPDATEDBY"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:tab-stops="left:335.25pt:space" xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt" start-indent="0.0pt">
                                       <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                          <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv2">
                                             <xsl:value-of select=".//ancestor-or-self::*/LASTUPDATEDATE" xdofo:field-name="ancestor-or-self::*/LASTUPDATEDATE"/>
                                          </xsl:variable>
                                          <xsl:value-of select="xdoxslt:ms_format_date($_XDOXSLTCTX, string($fv2), 'yyyy-MM-dd')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:tab-stops="left:335.25pt:space" xdofo:xliff-note="RESPONSIBILITY_KEY" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt" start-indent="0.0pt">
                                       <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                          <xsl:value-of select=".//RESPONSIBILITY_KEY" xdofo:field-name="RESPONSIBILITY_KEY"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="ACCESSIBILITY" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt" start-indent="0.0pt">
                                       <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                          <xsl:value-of select=".//ACCESSIBILITY" xdofo:field-name="ACCESSIBILITY"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="REASON, E, E" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt" start-indent="0.0pt">
                                       <fo:inline height="9.0pt" font-family="Arial" white-space-collapse="false" font-size="9.0pt">
                                          <xsl:value-of select=".//REASON" xdofo:field-name="REASON"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                              </fo:table-row>
                           </xsl:for-each>
                        </xsl:for-each>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt" font-size="12.0pt" height="13.392pt" font-family="Times New Roman"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt">
                  <!--RTF Template: $Header: FNDW3H_F_U.rtf 120.7 2008/11/06 23:13  spakanat  $-->
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
