  CREATE OR REPLACE EDITIONABLE VIEW "ADS_BI_HRV_COMP_LEVEL" ("COMPETENCE_NAME", "DATE_FROM", "DATE_TO", "PERSON_ID", "BUSINESS_GROUP_NAME", "PROFICIENCY_LEVEL") AS
  SELECT O101768.COMPETENCE_NAME,
O101768.DATE_FROM,
NVL(O101768.DATE_TO,NULL) DATE_TO,
O101768.PERSON_ID,
O101768.BUSINESS_GROUP_NAME,
O101768.PROFICIENCY_LEVEL
FROM HRFG_COMPETENCE_PROFILES O101768
WHERE ((SYSDATE BETWEEN DATE_FROM and DATE_TO) OR (SYSDATE >= DATE_FROM and DATE_TO is Null))
 ;
