  CREATE OR REPLACE EDITIONABLE PROCEDURE "FA_SYSTEM_CONTROLS_ADP" (A0 IN VARCHAR2,JB IN NUMBER,JC IN DATE,JD IN NUMBER,JF IN NUMBER,JG IN NUMBER,
JH IN NUMBER,JJ IN NUMBER,JK IN NUMBER,JL IN DATE,JM IN NUMBER,
JN IN NUMBER,JP IN DATE,JQ IN NUMBER,JR IN NUMBER,JS IN VARCHAR2,
JT IN VARCHAR2,JV IN VARCHAR2,JW IN VARCHAR2,JX IN VARCHAR2,JZ IN VARCHAR2,
J0 IN VARCHAR2,J1 IN VARCHAR2,J2 IN VARCHAR2,J3 IN VARCHAR2,J4 IN VARCHAR2,
J5 IN VARCHAR2,J6 IN VARCHAR2,J7 IN VARCHAR2,J8 IN VARCHAR2,J9 IN VARCHAR2,
KB IN NUMBER,KC IN VARCHAR2,KD IN NUMBER,KF IN VARCHAR2,E0 IN VARCHAR2,RB IN NUMBER,RC IN DATE,RD IN NUMBER,RF IN NUMBER,RG IN NUMBER,
RH IN NUMBER,RJ IN NUMBER,RK IN NUMBER,RL IN DATE,RM IN NUMBER,
RN IN NUMBER,RP IN DATE,RQ IN NUMBER,RR IN NUMBER,RS IN VARCHAR2,
RT IN VARCHAR2,RV IN VARCHAR2,RW IN VARCHAR2,RX IN VARCHAR2,RZ IN VARCHAR2,
R0 IN VARCHAR2,R1 IN VARCHAR2,R2 IN VARCHAR2,R3 IN VARCHAR2,R4 IN VARCHAR2,
R5 IN VARCHAR2,R6 IN VARCHAR2,R7 IN VARCHAR2,R8 IN VARCHAR2,R9 IN VARCHAR2,
SB IN NUMBER,SC IN VARCHAR2,SD IN NUMBER,SF IN VARCHAR2)
AS
NXT NUMBER;
CMT NUMBER;
NUSER varchar2(61);
newTRUE_NULLS VARCHAR2(250);
BEGIN
NXT:=FND_AUDIT_SEQ_PKG.NXT;
CMT:=FND_AUDIT_SEQ_PKG.CMT;
NUSER:=FND_AUDIT_SEQ_PKG.USER_NAME;
SELECT decode(A0,NULL,'Y','N')
||decode(JB,NULL,'Y','N')
||decode(JC,NULL,'Y','N')
||decode(JD,NULL,'Y','N')
||decode(JF,NULL,'Y','N')
||decode(JG,NULL,'Y','N')
||decode(JH,NULL,'Y','N')
||decode(JJ,NULL,'Y','N')
||decode(JK,NULL,'Y','N')
||decode(JL,NULL,'Y','N')
||decode(JM,NULL,'Y','N')
||decode(JN,NULL,'Y','N')
||decode(JP,NULL,'Y','N')
||decode(JQ,NULL,'Y','N')
||decode(JR,NULL,'Y','N')
||decode(JS,NULL,'Y','N')
||decode(JT,NULL,'Y','N')
||decode(JV,NULL,'Y','N')
||decode(JW,NULL,'Y','N')
||decode(JX,NULL,'Y','N')
||decode(JZ,NULL,'Y','N')
||decode(J0,NULL,'Y','N')
||decode(J1,NULL,'Y','N')
||decode(J2,NULL,'Y','N')
||decode(J3,NULL,'Y','N')
||decode(J4,NULL,'Y','N')
||decode(J5,NULL,'Y','N')
||decode(J6,NULL,'Y','N')
||decode(J7,NULL,'Y','N')
||decode(J8,NULL,'Y','N')
||decode(J9,NULL,'Y','N')
||decode(KB,NULL,'Y','N')
||decode(KC,NULL,'Y','N')
||decode(KD,NULL,'Y','N')
||decode(KF,NULL,'Y','N') INTO newTRUE_NULLS FROM SYS.DUAL;
IF(newTRUE_NULLS='NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN')THEN
newTRUE_NULLS:= NULL;
END IF;
INSERT INTO FA_SYSTEM_CONTROLS_A
VALUES(SYSDATE,'D',NUSER,newTRUE_NULLS,
USERENV('SESSIONID'),NXT,CMT,(TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'))*100000+MOD(NXT,100000)) * 100000 + USERENV('SESSIONID'),
A0,JB,JC,JD,JF,JG,
JH,JJ,JK,JL,JM,
JN,JP,JQ,JR,JS,
JT,JV,JW,JX,JZ,
J0,J1,J2,J3,J4,
J5,J6,J7,J8,J9,
KB,KC,KD,KF);
END FA_SYSTEM_CONTROLS_ADP;
/
