--CREATE CREATE OR REPLACE PROCEDURE "TSGS_UNDO_RETENTION" IS
CREATE OR REPLACE PROCEDURE "TSGS_UNDO_RETENTION" IS
v_sql_stmt VARCHAR2(250) := 'ALTER system SET undo_retention = 24000';
BEGIN
EXECUTE IMMEDIATE v_sql_stmt;
END tsgs_undo_retention;
/
