CREATE OR REPLACE VIEW "XXAPL_MM_OPEN_PO_DETAILS_V" ("DIVISION", "MASTER_ORG", "PO_HEADER_ID", "PO_NUMBER", "ORDER_DATE", "RELEASE_NUM", "LINE_NUM", "SHIPMENT_NUM", "ITEM_CODE", "ITEM_DESCRIPTION", "UOM", "QUANTITY_DUE", "SHIP_TO_ORG", "QTY_RCV_TOLERANCE", "VENDOR_NAME", "VENDOR_SITE_CODE", "VENDOR_SITE_ADDRESS1", "VENDOR_SITE_ADDRESS2") AS
SELECT   (SELECT   NAME
FROM   APPS.HR_OPERATING_UNITS
WHERE   ORGANIZATION_ID = POH.ORG_ID)
DIVISION,
(SELECT   O.ORGANIZATION_CODE
FROM   APPS.JAI_CMN_INVENTORY_ORGS J,
APPS.ORG_ORGANIZATION_DEFINITIONS O
WHERE       J.MASTER_ORGANIZATION_ID = O.ORGANIZATION_ID
AND J.ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
AND J.LOCATION_ID = 0)
MASTER_ORG,
POH.PO_HEADER_ID,
POH.SEGMENT1 PO_NUMBER,
POH.CREATION_DATE ORDER_DATE,
POR.RELEASE_NUM,
POL.LINE_NUM,
PLL.SHIPMENT_NUM,
--MSI.INVENTORY_ITEM_ID,
MSI.SEGMENT1 ITEM_CODE,
POL.ITEM_DESCRIPTION,
POL.UNIT_MEAS_LOOKUP_CODE UOM,
(PLL.QUANTITY - NVL (PLL.QUANTITY_RECEIVED, 0)) QUANTITY_DUE,
--PLL.SHIP_TO_ORGANIZATION_ID,
(SELECT   ORGANIZATION_CODE
FROM   APPS.ORG_ORGANIZATION_DEFINITIONS
WHERE   ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID)
SHIP_TO_ORG,
PLL.QTY_RCV_TOLERANCE,
PV.VENDOR_NAME,
PVS.VENDOR_SITE_CODE,
PVS.ADDRESS_LINE1
|| ' '
|| PVS.ADDRESS_LINE2
|| ' '
|| PVS.ADDRESS_LINE3
VENDOR_SITE_ADDRESS1,
PVS.CITY || ',' || PVS.STATE || ',' || PVS.ZIP
VENDOR_SITE_ADDRESS2
FROM   APPS.PO_HEADERS_ALL POH,
APPS.PO_LINES_ALL POL,
APPS.PO_LINE_LOCATIONS_ALL PLL,
APPS.PO_RELEASES_ALL POR,
APPS.MTL_SYSTEM_ITEMS_B MSI,
APPS.PO_VENDORS PV,
APPS.PO_VENDOR_SITES_ALL PVS
WHERE       POH.ORG_ID = 86
AND POH.AUTHORIZATION_STATUS = 'APPROVED'
--AND POL.CLOSED_CODE != 'CLOSED'
----AND PLL.CLOSED_CODE != 'CLOSED'
AND NVL (POL.CLOSED_FLAG, 'N') != 'Y'
AND NVL (PLL.CLOSED_FLAG, 'N') != 'Y'
AND NVL (POL.CANCEL_FLAG, 'N') != 'Y'
AND NVL (PLL.CANCEL_FLAG, 'N') != 'Y'
AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
AND POH.ORG_ID = PLL.ORG_ID
AND POH.PO_HEADER_ID = PLL.PO_HEADER_ID
AND POL.PO_LINE_ID = PLL.PO_LINE_ID
AND POR.PO_RELEASE_ID(+) = PLL.PO_RELEASE_ID
AND PLL.SHIP_TO_ORGANIZATION_ID = MSI.ORGANIZATION_ID
AND POL.ITEM_ID = MSI.INVENTORY_ITEM_ID
AND PLL.SHIP_TO_ORGANIZATION_ID IN (918, 921, 1140, 1141, 1534,1970)
AND PLL.QUANTITY - NVL (PLL.QUANTITY_RECEIVED, 0) != 0
AND POH.VENDOR_ID = PV.VENDOR_ID
AND POH.VENDOR_SITE_ID = PVS.VENDOR_SITE_ID
UNION ALL
SELECT   DISTINCT
(SELECT   NAME
FROM   APPS.HR_OPERATING_UNITS
WHERE   ORGANIZATION_ID =
(SELECT   OPERATING_UNIT
FROM   APPS.ORG_ORGANIZATION_DEFINITIONS
WHERE   ORGANIZATION_CODE = RCV.SHIP_TO_ORG))
DIVISION,
(SELECT   O.ORGANIZATION_CODE
FROM   Apps.JAI_CMN_INVENTORY_ORGS J,
APPS.ORG_ORGANIZATION_DEFINITIONS O
WHERE   J.MASTER_ORGANIZATION_ID = O.ORGANIZATION_ID
AND J.ORGANIZATION_ID =
(SELECT   ORGANIZATION_ID
FROM   APPS.ORG_ORGANIZATION_DEFINITIONS
WHERE   ORGANIZATION_CODE = RCV.SHIP_TO_ORG)
AND J.LOCATION_ID = 0)
MASTER_ORG,
WND.DELIVERY_ID PO_HEADER_ID,
WND.NAME PO_NUMBER,
WND.INITIAL_PICKUP_DATE ORDER_DATE,
NULL RELEASE_NUM,
RCV.LINE_NUM,
NULL SHIPMENT_NUM,
RCV.ITEM_CODE,
RCV.ITEM_DESCRIPTION,
RCV.UOM,
RCV.QUANTITY_DUE,
RCV.SHIP_TO_ORG,
NULL QTY_RCV_TOLERANCE,
HL.DESCRIPTION VENDOR_NAME,
HL.LOCATION_CODE VENDOR_SITE_CODE,
HL.ADDRESS_LINE_1
|| ','
|| HL.ADDRESS_LINE_2
|| ','
|| HL.ADDRESS_LINE_3
VENDOR_SITE_ADDRESS1,
HL.LOC_INFORMATION14
|| ','
|| HL.LOC_INFORMATION15
|| ','
|| HL.POSTAL_CODE
VENDOR_SITE_ADDRESS2
FROM   APPS.WSH_NEW_DELIVERIES WND,
APPS.WSH_DELIVERY_ASSIGNMENTS WDA,
APPS.WSH_DELIVERY_DETAILS WDD,
APPS.HR_LOCATIONS HL,
(SELECT   RSH.SHIPMENT_NUM,
RSL.LINE_NUM,
MSI.SEGMENT1 ITEM_CODE,
RSL.ITEM_DESCRIPTION,
RSL.UNIT_OF_MEASURE UOM,
(RSL.QUANTITY_SHIPPED - RSL.QUANTITY_RECEIVED)
QUANTITY_DUE,
(SELECT   OOD.ORGANIZATION_CODE
FROM   APPS.ORG_ORGANIZATION_DEFINITIONS OOD
WHERE   OOD.ORGANIZATION_ID = RSH.SHIP_TO_ORG_ID)
SHIP_TO_ORG
FROM   APPS.RCV_SHIPMENT_HEADERS RSH,
APPS.RCV_SHIPMENT_LINES RSL,
APPS.MTL_SYSTEM_ITEMS_B MSI
WHERE       RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID
AND RSH.SHIP_TO_ORG_ID IN (918, 921, 1140, 1141, 1534,1970)
AND RSH.RECEIPT_SOURCE_CODE = 'INTERNAL ORDER'
AND RSL.SHIPMENT_LINE_STATUS_CODE != 'FULLY RECEIVED'
AND RSL.ITEM_ID = MSI.INVENTORY_ITEM_ID
--AND RSH.SHIPMENT_NUM IN ('U07-D16/352', 'U07-D17/221', 'U07/17-18/1192')
AND MSI.ORGANIZATION_ID = 88) RCV
WHERE       WND.DELIVERY_ID = WDA.DELIVERY_ID
AND WDA.DELIVERY_DETAIL_ID = WDD.DELIVERY_DETAIL_ID
AND WND.NAME = RCV.SHIPMENT_NUM
AND WND.INITIAL_PICKUP_LOCATION_ID = HL.LOCATION_ID
ORDER BY   1,
              2,
              4,
              5,
              6,
              7 ;
