<?xml version = '1.0' encoding = 'utf-8'?>
<!--Generated by Oracle BI Publisher 10.1.3.4.2-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="66.6pt" margin-right="66.6pt" page-height="841.95pt" page-width="595.35pt" margin-top="36.0pt" margin-bottom="36.0pt">
               <fo:region-before region-name="region-header" extent="36.0pt"/>
               <fo:region-body region-name="region-body" margin-top="36.0pt" margin-bottom="36.0pt"/>
               <fo:region-after region-name="region-footer" extent="36.0pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(595.35)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(841.95)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header"/>
            <fo:static-content flow-name="region-footer"/>
            <fo:flow flow-name="region-body">
               <fo:block padding-bottom="0.25pt" padding-top="0.25pt">
                  <fo:table start-indent="-39.6pt" style-id="ts15" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="13.5pt"/>
                     <fo:table-column column-width="31.5pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="22.5pt"/>
                     <fo:table-column column-width="13.5pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="22.5pt"/>
                     <fo:table-column column-width="22.5pt"/>
                     <fo:table-column column-width="22.5pt"/>
                     <fo:table-column column-width="27.0pt"/>
                     <fo:table-column column-width="13.5pt"/>
                     <fo:table-column column-width="13.5pt"/>
                     <fo:table-column column-width="22.5pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="22.5pt"/>
                     <fo:table-column column-width="13.5pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="13.5pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="13.5pt"/>
                     <fo:table-column column-width="13.5pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="16.45pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="24" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt">
                              <fo:block height="14.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="16.45pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" number-columns-spanned="24" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-bottom="0.5pt solid #000000" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="16.0pt" white-space-collapse="false" font-size="16.0pt" color="#2e74b5" font-family="Calibri">Inventory Combined Report With FAB</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.85pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt">
                              <fo:block height="9.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Co Cd</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Organization Code </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Fg  Site</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">FG Pco Org </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Fg Item</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Fg Item Object Id</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">FG Item Product Family</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Subinventory Code </fo:inline>
                              </fo:block>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="9.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Fg Lot Number</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Fg item On-hand Quantity</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Assembly Item Object Id</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Assembly Item</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">Assembly Site</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item1</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item1 Lot Number</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item2</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item2 Lot Number</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item3</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item3 Lot Number</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="-0.9pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item4</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item4 Lot Number</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item5</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="74.6pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000" background-color="#bdd6ee">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" font-weight="bold" height="9.0pt" white-space-collapse="false" font-size="9.0pt" font-family="Calibri">DIE Item5 Lot Number</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                        <xsl:variable name="_XDOFOTOTAL" select="count(.//G_FG_INV_ITEM_ID)"/>
                        <xsl:for-each select=".//G_FG_INV_ITEM_ID" xdofo:ctx="3">
                           <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                           <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                           <fo:table-row xdofo:repeat="R">
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="18.15pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-bottom="0.5pt solid #000000" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt">
                                 <fo:block height="8.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                    <fo:inline xml:space="preserve" font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial"> <xsl:value-of select=".//CO_CD" xdofo:field-name="CO_CD"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//FG_INV_ORG_CODE" xdofo:field-name="FG_INV_ORG_CODE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//FG_INV_ORG_SITE" xdofo:field-name="FG_INV_ORG_SITE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//FG_PCO_ORG" xdofo:field-name="FG_PCO_ORG"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//FG_ITEM" xdofo:field-name="FG_ITEM"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//FG_ITEM_OBJECT_ID" xdofo:field-name="FG_ITEM_OBJECT_ID"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//PRODUCT_FAMILY" xdofo:field-name="PRODUCT_FAMILY"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//FG_SUBINV_CODE" xdofo:field-name="FG_SUBINV_CODE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//FG_LOT" xdofo:field-name="FG_LOT"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//FG_MOQ" xdofo:field-name="FG_MOQ"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//ASSY_OBJECT_ID" xdofo:field-name="ASSY_OBJECT_ID"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//ASSY_ITEM" xdofo:field-name="ASSY_ITEM"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//ASSY_INV_ORG_SITE" xdofo:field-name="ASSY_INV_ORG_SITE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//ITEM1" xdofo:field-name="ITEM1"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//LOT_NUMBER1" xdofo:field-name="LOT_NUMBER1"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//ITEM2" xdofo:field-name="ITEM2"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//LOT_NUMBER2" xdofo:field-name="LOT_NUMBER2"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//ITEM3" xdofo:field-name="ITEM3"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//LOT_NUMBER3" xdofo:field-name="LOT_NUMBER3"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//ITEM4" xdofo:field-name="ITEM4"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//LOT_NUMBER4" xdofo:field-name="LOT_NUMBER4"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//ITEM5" xdofo:field-name="ITEM5"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-bottom="0.0pt" border-start-color="#000000" height="17.9pt" vertical-align="top" border-end-color="#000000" padding-top="0.0pt" border-top="0.5pt solid #000000" number-columns-spanned="1" border-start-width="0.5pt" border-start-style="solid" border-end-width="0.5pt" border-end-style="solid" padding-start="5.15pt" padding-end="5.15pt" border-bottom="0.5pt solid #000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                    <fo:inline font-size="8.0pt" white-space-collapse="false" height="8.0pt" font-family="Arial">
                                       <xsl:value-of select=".//LOT_NUMBER5" xdofo:field-name="LOT_NUMBER5"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                        </xsl:for-each>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:12.95pt" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="8.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt" font-size="11.0pt" font-family="Calibri">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
